#ifndef BASICROBOT_H
#define BASICROBOT_H

#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/mman.h>
#include "include/dhdc.h"

#include "struct_shm.h"   // header generated by create_c_header.py

#define SHM_FILEPATH "/tmp/sharedmemory.bin" // the file path where shared memory is located (can be anything but needs to be the same as in sharedmem.py)

using namespace std;

class BasicRobot
{
 public:
  //Functions
  BasicRobot();
  virtual ~BasicRobot();
  void open_sharedmem();
  void flush_sharedmem();
  void close_sharedmem();
  void openDevice();
  void getPosition();
  void getVelocity();
  void closeDevice();
  bool keep_going();
  shm_t *getShm();
  void openDebug();
  void printDebug(const char* data,...);
  void closeDebug();
 protected:
  shm_t *sh_memory;
 private:
  FILE* debugfp;
  //ofstream debugfp;
  
};

#endif // BASICROBOT_H
